@extends('admin_client.admin_client')
@section('content')
@php $td=function($v){if(!$v)return '-';$d=$v instanceof \Carbon\CarbonInterface?$v:\Carbon\Carbon::parse($v);return $d->format('d/m/').($d->year+543);}; @endphp
<style>@page{size:A4 portrait;margin:12mm}.idpr{max-width:1000px;margin:auto}.idpr-toolbar{display:flex;justify-content:space-between;margin-bottom:12px}.idpr-paper{background:#fff;border:1px solid #dfe7f1;border-radius:14px;padding:24px}.idpr-sec{margin-top:18px}.idpr-sec h5{font-weight:800;border-bottom:2px solid #dbe8f7;padding-bottom:6px}.idpr-table{width:100%;border-collapse:collapse}.idpr-table th,.idpr-table td{border:1px solid #d8e1ea;padding:7px;font-size:.9rem;vertical-align:top}.idpr-table th{background:#f5f8fb}@media print{header,.navbar-custom,.leftside-menu,.footer,.idpr-toolbar{display:none!important}.content-page,.content,.container-fluid{margin:0!important;padding:0!important}.idpr-paper{border:0;padding:0}.idpr{max-width:none}}</style>
<div class="container-fluid py-3 idpr"><div class="idpr-toolbar"><a class="btn btn-outline-secondary" href="{{ route('individual-development.report.hub',['client'=>$client->id,'plan'=>$plan->id]) }}">กลับศูนย์รายงาน</a><button class="btn btn-primary" onclick="window.print()"><i class="bi bi-printer me-1"></i>พิมพ์ A4</button></div><div class="idpr-paper"><h3 class="fw-bold text-center">รายงานความก้าวหน้าแผนพัฒนารายบุคคล</h3><div class="text-center text-muted mb-3">{{ $client->fullname ?? $client->name ?? '-' }} • แผนครั้งที่ {{ $plan->plan_no }}</div>
<div class="idpr-sec"><h5>สรุปอัตโนมัติ</h5><p><strong>ประเด็นสำคัญ:</strong> {{ $caseSummary['problem'] }}</p><p><strong>การดำเนินงาน:</strong> {{ $caseSummary['actions'] }}</p><p><strong>ผล:</strong> {{ $caseSummary['result'] }}</p><p><strong>งานต่อไป:</strong> {{ $caseSummary['next'] }}</p></div>
<div class="idpr-sec"><h5>ความก้าวหน้าตามเป้าหมาย</h5><table class="idpr-table"><thead><tr><th>เป้าหมาย</th><th>สถานะ</th><th>ตัวชี้วัด</th><th>กิจกรรม/ผล</th></tr></thead><tbody>@forelse($goals as $g)<tr><td><strong>{{ $g->title }}</strong><br><span class="text-muted">{{ $g->description }}</span></td><td>{{ $goalStatusLabels[$g->status] ?? $g->status }}</td><td>{{ $g->success_indicator ?: '-' }}</td><td>@forelse($g->activities as $a)<div class="mb-2"><strong>{{ $td($a->activity_date) }}</strong> {{ $a->detail }} @if($a->result)<br>ผล: {{ $a->result }}@endif @if($a->next_action)<br>ทำต่อ: {{ $a->next_action }}@endif</div>@empty-@endforelse</td></tr>@empty<tr><td colspan="4" class="text-center">ยังไม่มีเป้าหมาย</td></tr>@endforelse</tbody></table></div>
<div class="idpr-sec"><h5>ประวัติการติดตาม</h5><table class="idpr-table"><thead><tr><th>ครั้ง/วันที่</th><th>สถานการณ์/การดำเนินงาน</th><th>ผล</th><th>สิ่งที่ต้องทำต่อ</th></tr></thead><tbody>@forelse($followups as $f)<tr><td>ครั้งที่ {{ $f->followup_no }}<br>{{ $td($f->followup_date) }}</td><td>{{ $f->current_situation ?: '-' }}@if($f->actions_taken)<br><strong>ดำเนินการ:</strong> {{ $f->actions_taken }}@endif</td><td>{{ $f->positive_changes ?: $f->result ?: ($followupResultLabels[$f->overall_result] ?? '-') }}</td><td>{{ $f->next_action ?: '-' }}@if($f->next_followup_date)<br>นัด {{ $td($f->next_followup_date) }}@endif</td></tr>@empty<tr><td colspan="4" class="text-center">ยังไม่มีการติดตาม</td></tr>@endforelse</tbody></table></div>
</div></div>
@endsection
