@extends('admin_client.admin_client')
@section('content')
@php
    $strengthLabels=['ability'=>'ความสามารถ/ความถนัด','interest'=>'ความสนใจ','hobby'=>'งานอดิเรก','talent'=>'ความสามารถพิเศษ','does_well'=>'สิ่งที่ทำได้ดี','dream'=>'ความฝัน','career_interest'=>'อาชีพที่สนใจ','trusted_person'=>'บุคคลที่ไว้วางใจ','motivation'=>'แรงจูงใจ','skills_to_promote'=>'ทักษะที่ควรส่งเสริม'];
    $structuredStrengths=collect($plan->strength_profile ?? [])->filter(fn($v)=>filled($v))->map(fn($v,$k)=>(($strengthLabels[$k] ?? $k).': '.$v))->values();
    $strengthReportText=filled($plan->strength_summary) ? $plan->strength_summary : ($structuredStrengths->isNotEmpty() ? $structuredStrengths->implode(' • ') : 'ยังไม่ได้ระบุ');
@endphp
<style>@page{size:A4 portrait;margin:14mm}.idprs{max-width:900px;margin:auto}.idprs-toolbar{display:flex;justify-content:space-between;margin-bottom:12px}.idprs-paper{background:#fff;border:1px solid #dfe7f1;border-radius:14px;padding:28px}.idprs-box{border:1px solid #dce6f0;border-radius:12px;padding:14px;margin-top:12px}.idprs-box h5{font-weight:800;color:#174f84}.idprs-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:700px){.idprs-grid{grid-template-columns:1fr}}@media print{header,.navbar-custom,.leftside-menu,.footer,.idprs-toolbar{display:none!important}.content-page,.content,.container-fluid{margin:0!important;padding:0!important}.idprs-paper{border:0;padding:0}.idprs{max-width:none}}</style>
<div class="container-fluid py-3 idprs"><div class="idprs-toolbar"><a class="btn btn-outline-secondary" href="{{ route('individual-development.report.hub',['client'=>$client->id,'plan'=>$plan->id]) }}">กลับศูนย์รายงาน</a><button class="btn btn-primary" onclick="window.print()"><i class="bi bi-printer me-1"></i>พิมพ์ A4</button></div><div class="idprs-paper"><h3 class="fw-bold text-center">รายงานสรุปผลรายบุคคล</h3><div class="text-center text-muted">{{ $client->fullname ?? $client->name ?? '-' }} • แผนครั้งที่ {{ $plan->plan_no }}</div><div class="alert alert-info py-2 small mt-3 mb-1"><i class="bi bi-pencil-square me-1"></i>ข้อความสรุป 4 ส่วนด้านล่างสามารถคลิกแก้ไขชั่วคราวก่อนพิมพ์ได้ โดยไม่เปลี่ยนข้อมูลต้นทาง</div>
<div class="idprs-grid mt-3"><div class="idprs-box"><h5>จุดแข็งและศักยภาพ</h5><div>{{ $strengthReportText }}</div></div><div class="idprs-box"><h5>ปัญหา/ความต้องการสำคัญ</h5><div contenteditable="true" title="คลิกเพื่อแก้ข้อความก่อนพิมพ์">{{ $caseSummary['problem'] }}</div></div></div>
<div class="idprs-box"><h5>การช่วยเหลือและการดำเนินงาน</h5><div contenteditable="true" title="คลิกเพื่อแก้ข้อความก่อนพิมพ์">{{ $caseSummary['actions'] }}</div></div>
<div class="idprs-box"><h5>ผลลัพธ์และความก้าวหน้า</h5><div contenteditable="true" title="คลิกเพื่อแก้ข้อความก่อนพิมพ์">{{ $caseSummary['result'] }}</div>@if($domainScores->isNotEmpty())<div class="row g-2 mt-2">@foreach($domainScores as $d)<div class="col-md-6"><div class="border rounded p-2"><strong>{{ $d['name'] }}</strong>: {{ $d['score']!==null?number_format($d['score'],2).'/5':'ยังไม่ประเมิน' }} @if($d['trend']==='up') <span class="text-success">↑ ดีขึ้น</span>@elseif($d['trend']==='down') <span class="text-danger">↓ ต้องติดตาม</span>@elseif($d['trend']==='same') <span class="text-muted">→ คงเดิม</span>@endif</div></div>@endforeach</div>@endif</div>
<div class="idprs-box"><h5>ข้อเสนอแนะและแผนต่อไป</h5><div contenteditable="true" title="คลิกเพื่อแก้ข้อความก่อนพิมพ์">{{ $caseSummary['next'] }}</div>@if($plan->final_recommendation)<div class="mt-2"><strong>ข้อเสนอแนะเมื่อสิ้นสุดแผน:</strong> {{ $plan->final_recommendation }}</div>@endif</div>
@if(is_array($plan->support_network_profile) && collect($plan->support_network_profile)->isNotEmpty())
<div class="idprs-box"><h5>เครือข่ายสนับสนุนและบุคคลสำคัญ</h5>@foreach($plan->support_network_profile as $network)<div class="mb-1"><strong>{{ data_get($network,'name') ?: data_get($network,'organization') ?: 'เครือข่ายสนับสนุน' }}</strong>@if(data_get($network,'organization')) • {{ data_get($network,'organization') }}@endif @if(data_get($network,'role')) — {{ data_get($network,'role') }}@endif</div>@endforeach</div>
@endif
@if(is_array($plan->discharge_plan_profile) && collect($plan->discharge_plan_profile)->filter(fn($v)=>filled($v))->isNotEmpty())
<div class="idprs-box"><h5>แผนก่อนจำหน่ายและติดตามหลังจำหน่าย</h5><div class="idprs-grid">@foreach(['housing_readiness'=>'ที่อยู่อาศัย','education_readiness'=>'การศึกษา','career_readiness'=>'อาชีพ','income_living_readiness'=>'รายได้/การดำรงชีวิต','caregiver_after_discharge'=>'ผู้ดูแลหลังจำหน่าย','receiving_agency'=>'หน่วยงานรับช่วงต่อ'] as $key=>$label)@if(filled(data_get($plan->discharge_plan_profile,$key)))<div><strong>{{ $label }}:</strong> {{ data_get($plan->discharge_plan_profile,$key) }}</div>@endif @endforeach</div>@if(filled(data_get($plan->discharge_plan_profile,'readiness_summary')))<div class="mt-2"><strong>สรุปความพร้อม:</strong> {{ data_get($plan->discharge_plan_profile,'readiness_summary') }}</div>@endif</div>
@endif
<div class="idprs-box"><h5>สรุปจากผู้ปฏิบัติงาน</h5><div>{{ $plan->final_outcome ?: ($latestFollowup?->suggestion ?: 'สามารถเพิ่มเติมความเห็นก่อนพิมพ์โดยแก้ข้อมูลในแผน/การติดตาม') }}</div></div>
</div></div>
@endsection
