@extends(config('university_tracking.client_layout', 'admin_client.admin_client'))
@section('content')
<link rel="stylesheet" href="{{ asset('backend/assets/css/university-tracking.css') }}">
<div class="container-fluid ut-page"><div class="ut-wrap py-3"><div class="ut-card ut-header"><div class="ut-title-row"><div class="ut-icon"><i class="bi bi-flag-fill"></i></div><div><h1 class="ut-title">{{ $isEdit ? 'แก้ไขผลสิ้นสุดการศึกษา' : 'บันทึกผลสิ้นสุดการศึกษา' }}</h1><p class="ut-subtitle">@include('university.partials.client_name',['client'=>$client]) · {{ $enrollment->university_name }}</p></div></div><div class="ut-actions"><a href="{{ route('university.enrollments.show',$enrollment->id) }}" class="ut-btn ut-btn-light"><i class="bi bi-x-lg"></i> ปิด</a></div></div>
@include('university.partials.validation')
<form method="POST" action="{{ $isEdit ? route('university.outcomes.update',$enrollment->id) : route('university.outcomes.store',$enrollment->id) }}" class="ut-card ut-content">@csrf @if($isEdit)@method('PUT')@endif
<div class="ut-grid"><div class="ut-field ut-col-4"><label>ผล/สถานะ <span class="ut-required">*</span></label><select class="form-select" name="outcome_type" id="outcomeType">@foreach(config('university_tracking.outcome_types') as $key=>$label)<option value="{{ $key }}" @selected(old('outcome_type',$outcome->outcome_type ?: 'graduated')===$key)>{{ $label }}</option>@endforeach</select></div><div class="ut-field ut-col-4"><label>วันที่</label><input type="date" max="{{ now('Asia/Bangkok')->toDateString() }}" class="form-control" name="outcome_date" value="{{ old('outcome_date',optional($outcome->outcome_date)->format('Y-m-d')) }}"></div><div class="ut-field ut-col-4"><label>ปีการศึกษา <span class="ut-required">*</span></label><input type="number" min="2400" max="2800" class="form-control" name="academic_year" value="{{ old('academic_year',$outcome->academic_year ?: now('Asia/Bangkok')->year+543) }}" required></div><div class="ut-field ut-col-4"><label>ภาคเรียน</label><select class="form-select" name="semester_id"><option value="">ไม่ระบุ</option>@foreach($semesters as $s)<option value="{{ $s->id }}" @selected((string)old('semester_id',$outcome->semester_id)===(string)$s->id)>{{ $s->semester_name }}</option>@endforeach</select></div><div class="ut-field ut-col-4"><label>GPA/GPAX สุดท้าย</label><input type="number" min="0" max="4" step="0.01" class="form-control" name="final_gpa" value="{{ old('final_gpa',$outcome->final_gpa) }}"></div></div>
<div class="ut-divider"></div><div id="graduatedFields"><h2 class="ut-section-title"><i class="bi bi-award"></i> ข้อมูลเมื่อสำเร็จการศึกษา</h2><div class="ut-grid"><div class="ut-field ut-col-4"><label>ปริญญาที่ได้รับ</label><input class="form-control" name="degree_name" value="{{ old('degree_name',$outcome->degree_name ?: $enrollment->degree_name) }}"></div><div class="ut-field ut-col-4"><label>เกียรตินิยม</label><input class="form-control" name="honors" value="{{ old('honors',$outcome->honors) }}"></div><div class="ut-field ut-col-4"><label>สถานะหลังจบ</label><select class="form-select" name="post_graduation_status"><option value="">ไม่ระบุ</option>@foreach(config('university_tracking.post_graduation_statuses') as $key=>$label)<option value="{{ $key }}" @selected(old('post_graduation_status',$outcome->post_graduation_status)===$key)>{{ $label }}</option>@endforeach</select></div><div class="ut-field ut-col-12"><label>รายละเอียดหลังจบ</label><textarea class="form-control" name="post_graduation_detail">{{ old('post_graduation_detail',$outcome->post_graduation_detail) }}</textarea></div></div></div>
<div id="reasonFields"><h2 class="ut-section-title"><i class="bi bi-sign-stop"></i> สาเหตุที่ไม่สำเร็จ/เปลี่ยนเส้นทาง</h2><div class="ut-help mb-2">กำหนดเหตุผลหลัก 1 ข้อ และเพิ่มเหตุผลร่วมได้ เพื่อใช้สรุปสถิติเด็กออกกลางคัน</div><div id="reasonRows"></div><button type="button" class="ut-btn ut-btn-light" id="addReason"><i class="bi bi-plus-circle"></i> เพิ่มเหตุผล</button></div>
<div class="ut-divider"></div><div class="ut-field"><label>สรุปผล</label><textarea class="form-control" name="summary" rows="4">{{ old('summary',$outcome->summary) }}</textarea></div><div class="ut-actions justify-content-end mt-3"><button class="ut-btn ut-btn-primary"><i class="bi bi-floppy"></i> บันทึกผลสิ้นสุด</button></div></form>@if($isEdit && $universityPermissions['delete'])<form method="POST" action="{{ route('university.outcomes.destroy',$enrollment->id) }}" class="ut-delete-form mt-3" data-message="ลบผลสิ้นสุดการศึกษานี้และเปลี่ยนสถานะกลับเป็นกำลังศึกษาหรือไม่?">@csrf @method('DELETE')<button class="ut-btn ut-btn-danger"><i class="bi bi-trash"></i> ลบผลสิ้นสุด</button></form>@endif</div></div>
@php $reasonSeed=old('reasons',$outcome->exists?$outcome->reasons->map(fn($r)=>$r->only(['reason_code','is_primary','detail']))->values()->all():[]); @endphp
<script>document.addEventListener('DOMContentLoaded',()=>{const type=document.getElementById('outcomeType'),g=document.getElementById('graduatedFields'),rf=document.getElementById('reasonFields'),root=document.getElementById('reasonRows');let rows=@json($reasonSeed);const reasons=@json(config('university_tracking.outcome_reasons'));function e(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function render(){root.innerHTML='';rows.forEach((r,i)=>{const d=document.createElement('div');d.className='ut-reason-row';d.innerHTML=`<button type="button" class="ut-row-remove" data-r="${i}"><i class="bi bi-x"></i></button><div class="ut-grid"><div class="ut-field ut-col-4"><label>เหตุผล</label><select class="form-select" name="reasons[${i}][reason_code]">${Object.entries(reasons).map(([k,v])=>`<option value="${k}" ${String(r.reason_code||'low_grade')===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="ut-field ut-col-3"><label>เหตุผลหลัก</label><div class="form-check mt-2"><input class="form-check-input primary-reason" type="checkbox" value="1" name="reasons[${i}][is_primary]" ${r.is_primary?'checked':''}><label class="form-check-label">ใช่</label></div></div><div class="ut-field ut-col-5"><label>รายละเอียด</label><input class="form-control" name="reasons[${i}][detail]" value="${e(r.detail)}"></div></div>`;root.appendChild(d)});root.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{rows.splice(Number(b.dataset.r),1);render()});root.querySelectorAll('.primary-reason').forEach(c=>c.onchange=()=>{if(c.checked)root.querySelectorAll('.primary-reason').forEach(o=>{if(o!==c)o.checked=false})})}function sync(){const grad=type.value==='graduated';g.style.display=grad?'block':'none';rf.style.display=grad?'none':'block'}document.getElementById('addReason').onclick=()=>{rows.push({reason_code:'low_grade',is_primary:rows.length===0});render()};if(!rows.length)rows.push({reason_code:'low_grade',is_primary:true});render();type.addEventListener('change',sync);sync();});</script>
@include('university.partials.delete_confirm')
@endsection
