@extends('admin_client.admin_client')
@section('content')
@php $thaiDate=function($v){if(!$v)return '-';$d=$v instanceof \Carbon\CarbonInterface?$v:\Carbon\Carbon::parse($v);return $d->format('d/m/').($d->year+543);}; @endphp
<style>.idpos{max-width:1400px;margin:auto}.idpos-card{background:#fff;border:1px solid #dfe7f1;border-radius:16px;padding:18px}.idpos-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.idpos-domain{border:1px solid #e2e8f0;border-radius:14px;padding:16px}.idpos-score{font-size:1.7rem;font-weight:800}.up{color:#15803d}.down{color:#b91c1c}.same{color:#64748b}@media(max-width:900px){.idpos-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.idpos-grid{grid-template-columns:1fr}}</style>
<div class="container-fluid py-3 idpos"><div class="idpos-card mb-3"><div class="d-flex justify-content-between gap-2 flex-wrap"><div><h4 class="fw-bold mb-1">{{ $typeLabels[$assessment->assessment_type] ?? $assessment->assessment_type }}</h4><div class="text-muted small">{{ $thaiDate($assessment->assessment_date) }} • ครั้งที่ {{ $assessment->round_no }} • แผนครั้งที่ {{ $plan->plan_no }}</div></div><div class="d-flex gap-2">@if($canUpdate)<a class="btn btn-outline-primary" href="{{ route('individual-development.outcomes.edit',[$client->id,$assessment->id]) }}"><i class="bi bi-pencil me-1"></i>แก้ไข</a>@endif<a class="btn btn-outline-secondary" href="{{ route('individual-development.outcomes.index',['client'=>$client->id,'plan'=>$plan->id]) }}">กลับ</a></div></div></div>
<div class="idpos-grid mb-3">@foreach($domainRows as $row)<div class="idpos-domain"><div class="fw-bold">{{ $row['name'] }}</div><div class="idpos-score">{{ $row['current']!==null?number_format($row['current'],2):'-' }} <span class="fs-6 text-muted">/5</span></div><div class="small">Baseline: {{ $row['baseline']!==null?number_format($row['baseline'],2):'-' }}</div><div class="small mt-1 @if($row['trend']==='up') up @elseif($row['trend']==='down') down @else same @endif">@if($row['delta']===null)ยังไม่มีค่าที่ใช้เปรียบเทียบ@elseif($row['delta']>0)↑ ดีขึ้น +{{ number_format($row['delta'],2) }}@elseif($row['delta']<0)↓ ต้องติดตาม {{ number_format($row['delta'],2) }}@else→ คงเดิม@endif</div></div>@endforeach</div>
<div class="idpos-card"><div class="row g-3"><div class="col-md-6"><div class="small text-muted">ความเห็นผู้รับบริการ/ผู้มีส่วนร่วม</div><div class="mt-1">{{ $assessment->participant_note ?: '-' }}</div></div><div class="col-md-6"><div class="small text-muted">สรุปผลโดยผู้ประเมิน</div><div class="mt-1">{{ $assessment->overall_note ?: '-' }}</div></div></div></div></div>
@if(session('success') || session('warning'))
<script>document.addEventListener('DOMContentLoaded',function(){if(window.Swal){Swal.fire({icon:@json(session('success')?'success':'warning'),title:@json(session('success')?'สำเร็จ':'แจ้งเตือน'),text:@json(session('success')??session('warning')),confirmButtonText:'OK',timer:3000,timerProgressBar:true});}});</script>
@endif
@endsection
